name: "action.yml"
on: push

jobs:
  docker-job:
    name: Docker job
    runs-on: ubuntu-latest
    container:
      image: rocker/r-ver:4.2.1
      volumes:
        - "${{ env.GITHUB_WORKSPACE }}:/home/r-ver"
    steps:
      - run: R --version
