name: "action.yml"
on: push

jobs:
  docker-job:
    name: Docker job
    runs-on: ubuntu-latest
    container:
      image: rocker/r-ver:4.2.1
    volumes:
      - ${GITHUB_WORKSPACE}
    steps:
      - uses: actions/checkout@v3
      - run: R --version
      - run: ls -alpF
